sonar.projectKey=openclassrooms-devops-training_projet3-datashare_frontend
sonar.projectName=DataShare Frontend
sonar.sources=src
sonar.exclusions=**/*.spec.ts
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
